[General]
DisplayServer=x11
Numlock=on
# Disable virtual keyboard. For additional info, see: https://askubuntu.com/a/1368158/4197
InputMethod=
# HaltCommand=
# RebootCommand=

[Theme]
Current=breeze
Font=Noto Sans CJK JP Medium
