# see man live-config
#LIVE_KEYBOARD_LAYOUTS=jp
#LIVE_KEYBOARD_MODEL=jp106
#LIVE_LOCALES=ja_JP.UTF-8
#LIVE_TIMEZONE=Asia/Tokyo
#LIVE_USERNAME=hdu
#LIVE_UTC=no
#LIVE_X_SESSION_MANAGER=plasmax11
#LIVE_USER_FULLNAME=Himeji-du User
#LIVE_HOSTNAME=medialab
