#!/bin/sh

set -e

lb config noauto \
    --distribution trixie \
    --architecture amd64 \
    --archive-areas "main contrib non-free non-free-firmware" \
    --chroot-squashfs-compression-type zstd \
    --bootappend-live "quiet splash boot=live components locales=ja_JP.UTF-8 timezone=Asia/Tokyo keyboard-model=jp106 keyboard-layouts=jp utc=no username=hdu hostname=medialab x-session-manager=plasmax11" \
    --iso-publisher "Himeji Dokkyo University" \
    --iso-volume "Himeji-du Live Linux" \
    --debian-installer live \
    "${@}"
